### ISSUE TITLE
Both CMAF and DASH are normative references for the use of the 'emsg' box

### ISSUE THREAD

**Issue by johnsim** [AOMediaCodec/av1-id3#14]
The emsg box is normatively defined in section 5.10.3.3 of ISO/IEC 23009-1:2017 (DASH), but section 7.4.5 of ISO/IEC 23000-19:2018 (CMAF) places additional constraints on the use of emsg boxes with CMAF. So both CMAF and DASH should be normative references in this metadata specification.

**Comment by cconcolato** [comment]
Discussed on March 3, 2020 and agreed. Editor(s) to implement.

**Comment by cconcolato** [comment]
Even if the syntax shows both versions of the emsg box, the statement above clearly mandates v1. 
> Version 1 of the Event Message box [DASH] must be used.

**Comment by krasimirkolarov** [comment]
Already implemented. Closing the issue.
